apiVersion: apps/v1
kind: Deployment
metadata:
  name: bottom-line-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bottom-line
  template:
    metadata:
      labels:
        app: bottom-line
    spec:
      containers:
        - name: bottom-line-container
          image: sharath71/sharath71-bottomline:bottomlinet3
          ports:
            - containerPort: 8080
        
            
